---
kind: Service
apiVersion: v1
metadata:
  name: app-1-service
spec:
  selector:
    app: app-1
  ports:
  - port: 80
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1-deployment
spec:
  selector:
    matchLabels:
      app: app-1
  replicas: 1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.12-alpine
        envFrom:
          - secretRef:
              name: secret-opaque
        env:
          - name: user-name
            valueFrom:
              secretKeyRef:
                name: secret-basic-auth
                key: username
        volumeMounts:
          - name: app-secrets
            mountPath: /etc/secrets
          - name: app-secrets-sample
            mountPath: /usr/share/nginx/html/.my-secure-id
            subPath: .my-secure-id
        ports:
        - containerPort: 80
      volumes:
       - name: app-secrets
         secret:
          secretName: secret-basic-auth
          items:
            - key: password
              path: .password
       - name: app-secrets-sample
         secret:
          secretName: secret-basic-auth
          items:
           - key: secure-id
             path: .my-secure-id