apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: t0p-Secret
data:
  secure-id: c2FtcGxlLXNlY3JldAo=   # it is allowed But atleast one username or password should present